config/routes.rb
Rails.application.routes.draw do
    root "pages#home"
    get 'pages/home', to: 'pages#home'

    resources :articles

    get '/signup', to: 'users#new'
    resources :users, except: [:new]

    get "/login", to: 'sessions#new'
    post "/login", to: 'sessions#create'
    delete "/logout", to: 'sessions#destroy'

    resources :topics

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 4 }
  validates :description, presence: true, length: { minimum: 6 }

  belongs_to :user
  validates :user_id, presence: true
  has_many :articlesprogramming_topics
  has_many :programming_topics, through: :articlesProgramming_topics
end

app/models/articles_programming_topic.rb
class ArticlesProgramming_topic < ApplicationRecord
  belongs_to :programming_topic
  belongs_to :article
end

app/models/programming_topic.rb
class Programming_Topic < ApplicationRecord
  has_many :articlesprogramming_topic
  has_many :articles, through: :articlesprogramming_topics
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255},
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_many :articles
  has_secure_password
  validates :password, presence: true, length: { minimum: 5 }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "you must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was created successfully"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was updated successfully!"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    Article.find(params[:id]).destroy
    flash[:success] = "Article deleted successfully"
    redirect_to articles_path
  end

  private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end

    def require_same_user
      if current_user != @article.user
        flash[:danger] = "You can only edit or delete your own recipes"
        redirect_to articles_path
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user
    else
      flash.now[:danger] = "There was somthing wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:edit, :update, :show]

  def index
    @topics = Programming_Topic.all
  end

  def new
  end

  def create
  end

  def edit
  end

  def show
    @programming_topic_articles = @programming_topic_articles.all
  end

  def set_topic
    @topics = Programming_Topic.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user , only: [:show, :edit, :update]
  before_action :require_same_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome #{@user.name} to the Wiki App"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:danger] = "You can only edit your own account"
      redirect_to users_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
  <% if @article.errors.any? %>
    <div class="row">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(@article.errors.count, "error") %> Prevented this <%= @article.class %> from being saved:
          </h2>
        <div class="panel-body">
         <ul>
           <% @article.errors.full_messages.each do |msg| %>
             <li><%= msg %></li>
           <% end %>
         </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

    <%= form_for @article do |f| %>

    <b><%= f.label :title %></b><br>
    <%= f.text_field :title, rows:1, class: "form-control", placeholder: "Enter Title of article" %>

    <br>
    <br>

    <b><%= f.label :description, "Write your article here" %></b><br>
    <%= f.trix_editor :description, rows: 30, class: "form-control", placeholder: "Enter Article Description" %>

    <br>
    <br>

    <%= f.submit class: "btn btn-primary btn-lg btn-block" %>

  <% end %>
  <div class="col-md-4 col-md-offset-4">
    <%= link_to "Cancel and return to articles listing", articles_path %>
 </div>
</div>

app/views/articles/edit.html.erb
<div id="article_show_content" class="skinny_wrapper
wrapper_padding">
  <h1 id="page_title">Edit An Exisiting Article</h1>

  <%= render 'form' %>

app/views/articles/index.html.erb
<div class="container">
  <h1 id="page_title">All Articles</h1>
    <thead>
     <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Author</th>
          <th>Created</th>
        </tr>
    </thead>

    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td><%= link_to article.title, article_path(article) %></td>
          <td><%= truncate(article.description.html_safe, length: 100) %></td>
          <td><%= article.user.name %></td>
          <td><%= time_ago_in_words(article.created_at) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/articles/new.html.erb
<div id="article_show_content" class="skinny_wrapper
wrapper_padding">
  <h1 id="page_title">Create New Article</h1>

  <%= render 'form' %>

app/views/articles/show.html.erb
<div id="article_show_content" class="skinny_wrapper
wrapper_padding">
  <header>
    <p class="date"><%= @article.created_at.strftime('%A, %B %d') %></p>
    <br>

    <h1><b><%= @article.title.capitalize %></b></h1>
    <hr>
  </header>

  <div id="description">
    
     <%= sanitize @article.description, tags: %w(strong em p br div ul ol li) %>﻿
  </div>

  <hr>
  <p class="date">Created by: <%= @article.user.name %></p>

  <div id="admin_links">
    <% if logged_in? && current_user == @article.user %>
    <%= link_to "Edit Article", edit_article_path(@article), class: "btn btn-primary" %>
    <%= link_to "Delete Article", article_path(@article), method: :delete, data: { confirm: 'Are you sure you want to delete this article?' }, class: "btn btn-danger" %>

    <% end %>

    <%= link_to "Return to articles listing", articles_path, class: "btn btn-success" %>
    </div>
  </div>

app/views/layouts/_messages.html.erb
<div class="row">
    <% flash.each do | name, msg | %>
    <div align="center">
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= msg %>
      </div>
    </div>
    <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Wiki" , root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "All Posts", articles_path %></li>
          <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" 
            role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name.capitalize %>'s Profile 
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
               <li><%= link_to "Create new article", new_article_path %></li>
              <li><%= link_to "View your profile", 
                                user_path(current_user) %></li>
              <li><%= link_to "Edit your profile", 
                                edit_user_path(current_user) %></li>
             <li><%= link_to 'Log out', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://use.fontawesome.com/f40685afe6.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="trix.css">
    <script type="text/javascript" src="trix.js"></script>

    <title>Wiki</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
   
     <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="starter-template">
    <h1>Wiki <i class="fa fa-code" aria-hidden="true"></i></h1>
      <h2 class="lead">Use this app to view internal documentation<br> and code snippets. Quickly start any new project.</h2>
      <p><%= link_to "View All Articles", articles_path, class: "btn btn-danger btn-lg btn-xlarge" %> &nbsp;
       <%= link_to "Sign Up Today", signup_path, class: "btn btn-primary btn-lg btn-xlarge" %></p>
</div>

app/views/topics/index.html.erb
<div class="container">
  <h1 id="page_title">All Topics</h1>
     <table class="table">
      <thead>
        <tr>
          <th>Topic</th>
        </tr>
    </thead>

    <tbody>
      <% @topics.each do |programming_topic| %>
        <tr>
          <td><%= programming_topic.topic %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/topics/show.html.erb
<div id="article_show_content" class="skinny_wrapper
wrapper_padding">

<% if @programming_topic.articles.count ! = 0 %>
  <header>
    <p class="date">Article's containing <%= @programming_topic.topic %>'s articles</p>
  </header>
<% else %>
<p align="center">No Topics yet!</p>
<% end %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <div class="row">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(@user.errors.count, "error") %> Prevented this <%= @user.class %> from being saved:
          </h2>
        <div class="panel-body">
         <ul>
           <% @user.errors.full_messages.each do |msg| %>
             <li><%= msg %></li>
           <% end %>
         </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

    <%= form_for @user do |f| %>

    <b><%= f.label :name %></b><br>
    <%= f.text_field :name, rows:1, class: "form-control", placeholder: "Enter Your name" %>

    <br>
    

    <b><%= f.label :email, "Email" %></b><br>
    <%= f.email_field :email, class: "form-control", placeholder: "Enter Your Email" %>

    <br>

     <b><%= f.label :password, "Password" %></b><br>
    <%= f.password_field :password, class: "form-control", placeholder: "Please Create password" %>

    <br>

    <b><%= f.label :password_confirmation, "Password confirmation" %></b>

    <br>
    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Please confirm your password" %>

    <br>
    <br>

    <%= f.submit(@user.new_record? ? "Create my account" : "Update my account", 
                  class: 'btn btn-primary btn-lg') %>

  <% end %>

</div>

app/views/users/edit.html.erb
<div id="article_show_content" class="skinny_wrapper
wrapper_padding">
  <h1 id="page_title">Edit Your Profile</h1>

  <%= render 'form' %>

app/views/users/new.html.erb
<div id="article_show_content" class="skinny_wrapper
wrapper_padding">
  <h1 id="page_title">Sign Up</h1>

  <%= render 'form' %>

app/views/users/show.html.erb
<div class="container">
  <h1 id="page_title"><%= @user.name %>'s Articles</h1>
    <thead>
     <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Created</th>
        </tr>
    </thead>

    <tbody>
      <% @user.articles.each do |article| %>
        <tr>
          <td><%= link_to article.title, article_path(article) %></td>
          <td><%= truncate(article.description.html_safe, length: 100) %></td>
          <td><%= time_ago_in_words(article.created_at) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>